### ISSUE TITLE
Haplogroup classification issue in 1.1-beta

### ISSUE THREAD

**Issue by haansi** [mitobench/MitoBench#70]
Used data: 
https://github.com/apeltzer/mitoDB-data/blob/master/data/Modern/1000GP3/1000GP3.csv
https://github.com/apeltzer/mitoDB-data/blob/master/data/Modern/1000GP3/1000GP3.fasta

Clicked on Analysis -> Calculate Haplogroups
```
Writing fasta sequences to multifasta.fasta
Start haploGrep ....
Haplogroups are determined
java.io.FileNotFoundException: haplogroups.hsd (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at io.reader.HSDInput.<init>(HSDInput.java:31)
	at analysis.HaplotypeCaller.update(HaplotypeCaller.java:54)
	at view.menus.AnalysisMenu.lambda$null$1(AnalysisMenu.java:84)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:723)
	at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at analysis.HaplotypeCaller.update(HaplotypeCaller.java:60)
	at view.menus.AnalysisMenu.lambda$null$1(AnalysisMenu.java:84)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:723)
	at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JudithNeukamm** [comment]
I tried it as well and it worked. Hm...I will at least catch this error and hope to find the problem.

**Comment by haansi** [comment]
FYI: have to add that I tried it on ubuntu - could it be path related issues?

**Comment by JudithNeukamm** [comment]
I'm running it on Ubuntu as well.

**Comment by seppinho** [comment]
Maybe different Java versions? @haansi can you report your java and also javafx version. Using the same input files should reproduce the bug.

**Comment by haansi** [comment]
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

Ubuntu 18.04.2 LTS

**Comment by JudithNeukamm** [comment]
Please let me know if this error still occurs in newer versions.

**Comment by haansi** [comment]
Hi Judith, thanks, it works! Suggestion: For large datasets it would be nice to have a progressbar, or similar to see if the process is still running
