### ISSUE TITLE
Exception -> Import Data from DB 

### ISSUE THREAD

**Issue by haansi** [mitobench/MitoBench#71]
Import from Database takes ~2 mins to show the popup-window: 
 **Database search configurator** 

Selecting **[ x] get all data from DB** and clicking on Send (java -jar MitoBench-1.1-beta.jar)

Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
	at java.lang.StringCoding.decode(StringCoding.java:193)
	at java.lang.String.<init>(String.java:426)
	at java.lang.String.<init>(String.java:491)

Selecting **[ x] get all data from DB** and clicking on Send (java -jar -Xmx8g MitoBench-1.1-beta.jar) 

Exception in thread "JavaFX Application Thread" org.json.JSONException: JSONObject["accession_id"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at database.JsonDataParser.getData(JsonDataParser.java:25)
	at database.DatabaseQueryHandler.combineResults(DatabaseQueryHandler.java:92)
	at database.DatabaseQueryHandler.getAllData(DatabaseQueryHandler.java:30)

**Comment by JudithNeukamm** [comment]
Yes, I'm currently working on that and had to change the database model. Will publish a new and (working) release this afternoon.

**Comment by JudithNeukamm** [comment]
Hey Hansi, please try the new release version 1.2-beta. Let me know if there are still problems.

**Comment by haansi** [comment]
Hi Judith, very cool thanks!

1000G worked fine, full import however:

Runtime of getting data from database: 2 minutes, and 55 seconds.
Runtime of data import to mitoBench: 60 seconds.
Thereafter a popup appears: view.MitoBenchWindow is not responding - Force Quit or Wait

**Comment by JudithNeukamm** [comment]
Hi Hansi, 
unfortunately, I probably can't change the 2 minutes 55 seconds. If I use the university network, it takes 1 minute, at home about the same, so it seems to depend on the internet connection? The import into mitoBench (which is actually only the import into the configuration window) takes about 40 seconds for me.
I have also made the experience that sometimes it is faster and sometimes slower. Maybe it has something to do with the network where the database is located?

**Comment by seppinho** [comment]
Hi Judith, how is the download of the meta file working from a technical point of view? It this a static file on the server or created from the DB on the fly? Looks like there is also problem with the server configuration. Chrome reports HTTP Status 200 OK after a few seconds even if file is not fully downloaded. 
Maybe compressing the JSON helps:
https://coderwall.com/p/mekopw/jsonc-compress-your-json-data-up-to-80

**Comment by seppinho** [comment]
Any update on this one?

**Comment by JudithNeukamm** [comment]
Hey Sebastian, 
not yet, but I will check it asap.
